POST http://localhost:5000/product/
Content-Type: application/json

{
    "name": "Пекан",
    "category": "Горіхи",
    "title": "Пекан",
    "img": "https://res.cloudinary.com/dannh4de9/image/upload/v1717095932/organic/images_organic/nuts/asiylevgbsubpbpyz4my.jpg",
    "old_price": 385,
    "current_price": 357,
    "stars": 5,
    "slug": "pecans",
    "quantity": 1,
    "short_text": "Пекан - це велике маслянисте насіння дерева Carya illinoinensis, яке має смачний смак та використовується як закуска, а також в приготуванні кондитерських виробів, солодощів та випічки.",
    "full_text": "Пекан містить велику кількість омега-3 жирних кислот, білків, вітамінів та мінералів, таких як вітамін В1, магній та цинк. Калорійність пекану становить близько 691 ккал на 100 грамів. Він сприяє покращенню здоров'я серця, зниженню рівня холестерину та покращенню пам'яті.",
    "additional_info": "Пекан можна вживати як самостійну закуску, додавати до салатів, випічки та десертів. Рекомендується зберігати його в сухому та прохолодному місці для збереження свіжості та смаку."
    }